version: "3.8"
services:
  turismo-control:
    build: ./turismo-control
    ports:
      - "5000:8080"
    hostname: "turismo_control"
  dacs-mailer-db:
    extends:
      file: tp-dacs-2022-mailer/docker-compose.yml
      service: dacs_redis_db
    hostname: "dacs_redis_db"
  dacs-mailer-queue:
    extends:
      file: tp-dacs-2022-mailer/docker-compose.yml
      service: dacs_mail_queue
    ports:
      - "9231:9231"
    volumes:
      - ./tp-dacs-2022-mailer/src:/usr/src/app/src
    hostname: "dacs_mailer"
  dacs-external:
    build: ./tp-dacs-2022-external
    ports:
      - "4000:4000"
      - "9230:9230"
    volumes:
      - ./tp-dacs-2022-external/src:/usr/src/app/src
      - ./tp-dacs-2022-external/db:/usr/src/app/db
    hostname: "dacs_external"
  dacs-be:
    build: ./tp-dacs-2022-be
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./tp-dacs-2022-be/src:/usr/src/app/src
      - ./tp-dacs-2022-be/db:/usr/src/app/db
    hostname: "dacs_be"
  dacs_gateway:
    extends:
      file: tp-dacs-2022-fe/docker-compose.yml
      service: dacs_gateway
    ports:
      - "8080:8080"
    volumes:
      - ./tp-dacs-2022-fe/gateway/config.js:/rproxy/src/config.js
    hostname: "dacs_gateway"
  dacs_fe:
    extends:
      file: tp-dacs-2022-fe/docker-compose.yml
      service: dacs_fe
    ports:
      - "3000:3000"
    hostname: "dacs_fe"
